version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - PORT=8080
    volumes:
      - .:/usr/src/app
    command: npm start

networks:
  default:
    driver: bridge